"""S-74 — Eight sounds on eight events, and nine plays on the eight actions.

docs/E2E.md §6 S-74. Fixture F2. Required by AC-118. Serves Stage 2.

The eight assets are `RESEARCH.md` §3's observed list, generated by `tools/make_sounds.py` into
`web/public/sounds/` and shipped verbatim by Vite. `web/src/lib/sound.ts` is the whole play layer;
the call sites are `GoalCard.vue`, `GoalCardTools.vue` and `Column.vue`.

Nine plays across eight assets, not eight: action 8 is itself a check, so it fires `checked` and
then `all_completed`. S-74's own words — "asserting eight entries would fail a correct build".
`ACCEPTANCE.md` AC-118 still says eight; the correction is filed with the owner, and this file
follows S-74.

One deviation from S-74's step table is forced by the fixture and reported as a doc row rather
than papered over:

 1. **Steps 6 and 7 target `SYNMAY02`, not `SYNDAY01`.** S-74 asks for expand (6) then collapse
    (7) on `SYNDAY01`, then a check on `SYNSUB03` (8) — but `SYNSUB03` is drawn *inside*
    `SYNDAY01` and nowhere else (`store.ts::toCardData` nests vertical-NULL children only), so a
    collapsed `SYNDAY01` puts step 8's target in no DOM at all. The two steps cannot both hold on
    one card. Setup here gives `SYNMAY02` a nested child so it has a toggle of its own, leaving
    `SYNDAY01` expanded for step 8.
Parent cards ship collapsed, matching the reference measured in P-31. Setup therefore expands
`SYNDAY01` before recording so step 8's child is present; `SYNMAY02` remains untouched and
collapsed, making step 6's first click the required expand event. The recorder is cleared at the
line where step 1 begins.

Instrumentation entry 2 of E2E.md §1 (the audio recorder) is installed here rather than in
`tests/ui/conftest.py`: this is the only scenario in the package that touches audio, and the
conftest's own docstring states the recorder belongs with the scenario that justifies it.
"""

from __future__ import annotations

import time
from pathlib import Path
from urllib.parse import urlparse

import httpx
import psycopg
from playwright.sync_api import Response

from tests.harness.report import gate
from tests.ui.conftest import UiSession, activate_column

REPO_ROOT = Path(__file__).resolve().parents[2]
DIST = REPO_ROOT / "web" / "dist"

# `RESEARCH.md` §3's observed list, verbatim — the eight asset stems S-74 asserts across nine
# plays. Named here, not derived, because the gate reason has to name what is missing.
ASSET_STEMS = (
    "checked",
    "unchecked",
    "goal_dragging",
    "goal_deleted",  # legacy asset name; v2 uses it for Remove from vertical
    "add_goal_clicked",
    "vertical_expanded",
    "vertical_collapsed",
    "all_completed",
)

# S-74's assertion, in order. Nine entries, eight distinct.
EXPECTED_SEQUENCE = [
    "checked",
    "unchecked",
    "goal_dragging",
    "goal_deleted",
    "add_goal_clicked",
    "checked",
    "all_completed",
]

# Entry 2 of E2E.md §1: patch `HTMLMediaElement.prototype.play` to append `this.currentSrc` to
# `window.__audio`. Installed before app load so a play fired during boot is recorded too — S-74
# asserts `window.__audio` is empty after page load alone, which is only checkable if a boot-time
# play would have been caught.
_AUDIO_RECORDER_SCRIPT = """
(function () {
  window.__audio = [];
  var realPlay = HTMLMediaElement.prototype.play;
  HTMLMediaElement.prototype.play = function () {
    window.__audio.push(this.currentSrc || this.src || '');
    return realPlay.apply(this, arguments);
  };
})();
"""

# --- selectors ---------------------------------------------------------------------------------
# `> .goal-card__row` (direct child) everywhere a card has children, for the strict-mode reason
# `test_s64_complete_one_gesture.py` records in full: a nested subgoal's own row is a descendant
# of its parent's card. R3's kit-ext affordance wrapper is the click target; its nested input is
# retained only as a checked-state probe.
DON_ROW = '[data-goal-id="SYNDON01"] > .goal-card__row'
DON_AFFORDANCE = f'{DON_ROW} [data-role="goal-affordance"][data-affordance="leaf"]'
DON_CHECKBOX = f"{DON_AFFORDANCE} input.checkbox__input"
ORD04_ROW = '[data-goal-id="SYNORD04"] > .goal-card__row'
Q1_ROW = '[data-goal-id="SYNQ1R01"] > .goal-card__row'
ORD03_CARD = '[data-goal-id="SYNORD03"]'
CONTEXT_MENU = '[data-role="goal-context-menu"]'
DAY_ADD = '[data-vertical="day"] [data-role="column-add"][data-cap="create-goal"]'
DAY_ADD_EDITOR = '[data-vertical="day"] [data-cap="create-goal"] input.column-add-editor'
SUB03_AFFORDANCE = (
    '[data-goal-id="SYNSUB03"] > .goal-card__row '
    '[data-role="goal-affordance"][data-affordance="leaf"]'
)

# The grip point for the drag, in card-local pixels — `test_s67_reparent_two_gestures.py`'s own
# GRIP, and its reasoning: a card row is `checkbox | text | schedule trigger` on one flex line and
# only the middle strip is inert.
GRIP = {"x": 50, "y": 6}

NEW_TITLE = "S-74 add probe"


def _dist_audio_files() -> list[str]:
    """Every file under the built `dist/` whose name looks like an audio asset. Reads the real
    build output on disk, not the source tree — S-74 asserts the *shipped* assets return 200."""
    if not DIST.exists():
        return []
    suffixes = {".mp3", ".wav", ".ogg", ".m4a", ".aac", ".flac", ".opus", ".webm"}
    return sorted(p.name for p in DIST.rglob("*") if p.is_file() and p.suffix.lower() in suffixes)


def _api(session: UiSession, method: str, path: str, json: dict) -> None:
    """One setup write through the real HTTP API — the same routes the browser uses, same token,
    no mock and no direct INSERT. `httpx` is already this suite's own client (`conftest.py`)."""
    response = httpx.request(
        method,
        f"{session.backend.base_url}{path}",
        json=json,
        headers={"Authorization": f"Bearer {session.backend.token}"},
        timeout=10.0,
    )
    assert response.status_code < 400, f"setup {method} {path} failed: {response.status_code} {response.text}"


def _stem(url: str) -> str:
    return Path(urlparse(url).path).stem


def test_s74_eight_sounds(ui_f2: UiSession) -> None:
    session = ui_f2
    page = session.page

    # Response log for the asset requests specifically. `session.request_log` carries the
    # *request* headers; S-74 asks for the response status and a non-zero `Content-Length`, which
    # is what this records. Installed before the reload that fetches them.
    asset_responses: list[dict] = []

    def on_response(res: Response) -> None:
        if "/sounds/" not in res.url:
            return
        asset_responses.append(
            {
                "url": res.url,
                "status": res.status,
                "content_length": res.header_value("content-length"),
            }
        )

    page.on("response", on_response)

    # --- setup, before recording ----------------------------------------------------------------
    # S-74's own: "close SYNSUB01 and SYNSUB02 before recording, so the eighth action is the one
    # that empties the parent", plus reopening SYNDON01 so step 1 has something to check.
    _api(session, "PATCH", "/api/goals/SYNSUB01", {"done": True})
    _api(session, "PATCH", "/api/goals/SYNSUB02", {"done": True})
    _api(session, "PATCH", "/api/goals/SYNDON01", {"done": False})
    for child_id in ("SYNSUB01", "SYNSUB02", "SYNSUB03"):
        _api(
            session, "PUT", f"/api/goals/{child_id}/schedule",
            {"vertical": "day", "anchor_date": "2026-08-08"},
        )
    # The recorder has to be live from before the app's own boot, and the fixture already
    # navigated once. Install it, then reload so this page load runs with it in place.
    session.context.add_init_script(script=_AUDIO_RECORDER_SCRIPT)
    page.reload()
    page.wait_for_selector('[data-goal-id="SYNDAY01"]', timeout=10000)
    # D244: the SYNSUB rows fold into SYNDAY01's compact stack until the day column expands.
    activate_column(page, "day")
    page.wait_for_selector(SUB03_AFFORDANCE, timeout=10000)

    played_on_load = page.evaluate("window.__audio || []")
    dist_audio = _dist_audio_files()

    # Does the shipped bundle so much as construct an audio element? `"checked"` and friends are
    # substrings of unrelated identifiers (`KCheckbox`'s own `checked` prop), so a bare name scan
    # reports false positives — the probe is for the *mechanism*: `new Audio(...)`, an
    # `<audio>` element, or a `.play()` on a media element.
    bundle_text = "\n".join(
        p.read_text(errors="ignore") for p in DIST.rglob("*.js") if p.is_file()
    ) if DIST.exists() else ""
    plays_audio = any(
        marker in bundle_text
        for marker in ("new Audio(", 'createElement("audio")', "createElement('audio')", "HTMLMediaElement")
    )
    # Only meaningful once audio exists — a name scan on a bundle that has no audio mechanism at
    # all reports `KCheckbox`'s `checked`, not an asset.
    named_in_bundle = [stem for stem in ASSET_STEMS if stem in bundle_text] if plays_audio else []

    if not dist_audio and not plays_audio:
        gate(
            "the app ships no audio at all — `web/dist/` contains zero audio files and the built "
            "bundle never constructs an audio element (no `new Audio(`, no `createElement(\'audio\')`, "
            "no `HTMLMediaElement` reference), so none of RESEARCH.md §3's eight asset names "
            f"({', '.join(ASSET_STEMS)}) can be playing, and no gesture can fire a sound. S-74 "
            "needs those eight assets shipped and served, plus a play call wired to each of: "
            "check, uncheck, drag between columns, delete a leaf, inline add, expand, collapse, "
            "and closing the last open child of a parent (which fires two — `checked` then "
            "`all_completed`, nine plays across the eight actions)"
        )

    # Reached only once the eight assets ship: the recorder is installed and the page is loaded,
    # so the scenario's own first assertion is checkable here.
    assert played_on_load == [], f"audio played on page load alone: {played_on_load}"
    missing = [stem for stem in ASSET_STEMS if stem not in named_in_bundle]
    assert missing == [], f"the build ships audio but not these S-74 assets: {missing}"

    # D142: board hierarchy is always expanded and exposes no collapse icon.
    assert page.locator('[data-role="subgoal-toggle"]').count() == 0

    # ==============================================================================================
    # Recording starts here. Nine plays, eight actions, in S-74's order.
    # ==============================================================================================
    page.evaluate("window.__audio = []")
    conn = psycopg.connect(session.backend.dsn, autocommit=True)
    try:
        # 1 — check SYNDON01 (reopened in setup above).
        assert not page.locator(DON_CHECKBOX).is_checked(), "setup failed: SYNDON01 is still closed"
        session.gestures.click(DON_AFFORDANCE)
        _wait_for_plays(page, 1)

        # 2 — uncheck it again.
        session.gestures.click(DON_AFFORDANCE)
        _wait_for_plays(page, 2)

        # 3 — drag SYNORD04 out of the week column onto a quarter parent. A drop is what makes a
        # drag a drag (`GoalCard.vue`'s own note on why the sound is not on the mousedown).
        page.keyboard.down("Alt")
        try:
            session.gestures.drag(ORD04_ROW, Q1_ROW, source_position=GRIP, target_position=GRIP)
        finally:
            page.keyboard.up("Alt")
        _wait_for_plays(page, 3)
        deadline = time.monotonic() + 5
        while time.monotonic() < deadline:
            (parent,) = conn.execute("SELECT parent_id FROM goals WHERE id = 'SYNORD04'").fetchone()
            if parent == "SYNQ1R01":
                break
            page.wait_for_timeout(100)
        assert parent == "SYNQ1R01", f"the drag did not reparent SYNORD04 (parent_id={parent!r})"

        # 4 — v2 removal gesture. Delete left the stamped unified menu; Remove from vertical is its
        # non-destructive successor and retains the legacy removal sound asset.
        activate_column(page, "week")
        page.locator(ORD03_CARD).click(button="right")
        page.wait_for_selector(CONTEXT_MENU)
        session.gestures.click(f'{CONTEXT_MENU} [data-menu-item="park"]')
        _wait_for_plays(page, 4)
        page.wait_for_selector('[data-goal-id="SYNORD03"]', state="detached", timeout=5000)
        deadline = time.monotonic() + 5
        parked = conn.execute(
            "SELECT vertical, parked_from_vertical FROM goals WHERE id = 'SYNORD03'"
        ).fetchone()
        while parked != (None, "week") and time.monotonic() < deadline:
            page.wait_for_timeout(50)
            parked = conn.execute(
                "SELECT vertical, parked_from_vertical FROM goals WHERE id = 'SYNORD03'"
            ).fetchone()
        assert parked == (None, "week")

        # 5 — the inline add row of the day column. Typing is not a gesture; Enter commits.
        session.gestures.click(DAY_ADD)
        page.locator(DAY_ADD_EDITOR).wait_for(state="visible")
        page.locator(DAY_ADD_EDITOR).press_sequentially(NEW_TITLE)
        session.gestures.press_committing(DAY_ADD_EDITOR, "Enter")
        _wait_for_plays(page, 5)

        # D142 retires expand/collapse board actions. Close the last open child next.
        # SYNSUB01/02 are already closed, so this is
        # the check that empties SYNDAY01: two plays, `checked` then `all_completed`.
        session.gestures.click(SUB03_AFFORDANCE)
        _wait_for_plays(page, 7)

        # --- the assertion ------------------------------------------------------------------------
        recorded = page.evaluate("window.__audio || []")
        stems = [_stem(url) for url in recorded]
        assert stems == EXPECTED_SEQUENCE, (
            f"S-74's nine plays came out as {stems}, expected {EXPECTED_SEQUENCE}"
        )
        assert len(set(recorded)) == 6, (
            f"expected 6 active board-event asset URLs, got {len(set(recorded))}: "
            f"{sorted(set(recorded))}"
        )

        # Every one of the eight was really served, with a body.
        #
        # Two separate facts, deliberately measured two different ways (D95):
        #
        #   1. the app ASKED for it — read off the page's own response log, which is the only
        #      place that can prove the audio element issued the request;
        #   2. the URL SERVES a real body — fetched once here, directly, and the body counted in
        #      bytes.
        #
        # (2) is not read off the response log any more. A `Content-Length` header is a property of
        # a particular HTTP exchange, not of the asset: an `HTMLAudioElement` may fetch a source
        # several times (a range probe, the real read, a replay served out of the browser cache),
        # and a cache-served response carries no length at all. D92 tried to survive that by taking
        # the best entry per URL and it still failed the next full run with a single cached entry
        # (`Content-Length values: [None]`), because on that run the browser never went to the
        # network for that sound twice. An assertion whose truth depends on whether a cache happened
        # to be warm proves nothing about the build.
        #
        # `page.request` is the context's own API request path, not the page's — it does not consult
        # the page cache, so this is a real fetch of the real URL every time, and `len(body)` is the
        # byte count rather than a header's claim about it. S-74's "returned HTTP 200" is measured
        # as 200 here (a plain GET, no `Range` header, so no 206 — the 206 in the response log is
        # the media element's own doing and is checked where it belongs, in (1)).
        by_url: dict[str, list[dict]] = {}
        for entry in asset_responses:
            by_url.setdefault(entry["url"], []).append(entry)
        for url in sorted(set(recorded)):
            entries = by_url.get(url)
            assert entries, f"{url} played but was never requested over the network"
            for entry in entries:
                assert entry["status"] in (200, 206), (
                    f"{url} returned HTTP {entry['status']} to the page, expected 200 or 206 "
                    f"(206 is normal: a media element fetches its source with a `Range` header)"
                )
            served = page.request.get(url)
            assert served.status == 200, (
                f"{url} fetched directly returned HTTP {served.status}, expected 200"
            )
            assert len(served.body()) > 0, f"{url} is served with an empty body"

        # No modal opened at any point — the whole scenario is board-surface gestures.
        assert session.dialog_records() == [], f"a modal opened during S-74: {session.dialog_records()}"

        # And the state the last two plays claim is the state on disk. Polled, not read once:
        # `store.ts::completeGoal` mutates optimistically *before* awaiting the PATCH (its own
        # header comment), which is exactly why the sound fires ahead of the write — so a single
        # read here races the request that has not landed yet. Measured: it lost that race in a
        # full-suite run and won it running alone.
        deadline = time.monotonic() + 5
        while time.monotonic() < deadline:
            rows = dict(
                conn.execute(
                    "SELECT id, done_at IS NOT NULL FROM goals WHERE parent_id = 'SYNDAY01'"
                ).fetchall()
            )
            if rows and all(rows.values()):
                break
            page.wait_for_timeout(100)
        assert rows and all(rows.values()), f"SYNDAY01 still has open children: {rows}"
    finally:
        conn.close()


def _wait_for_plays(page, count: int, timeout_ms: int = 5000) -> None:
    """Wait until the recorder holds exactly `count` entries. A play is issued synchronously in
    the click handler, but the click itself returns to Python through the driver, so the read has
    to be a poll — `page.wait_for_function`, never a bare `time.sleep` (see `UiSession`'s own note
    on why sleeping never lets the driver dispatch)."""
    page.wait_for_function(
        "expected => (window.__audio || []).length >= expected", arg=count, timeout=timeout_ms
    )
    actual = page.evaluate("(window.__audio || []).length")
    assert actual == count, (
        f"expected {count} plays by this point, the recorder holds {actual}: "
        f"{[_stem(u) for u in page.evaluate('window.__audio || []')]}"
    )
